export * from './api/client'
export * from './api/errors'

export * as courseCatalog from './courseCatalogApi'
export * as curriculumPersistence from './curriculumPersistenceApi'
export * as curriculumPlanner from './curriculumPlannerApi'
export * as curriculumPrerequisites from './curriculumPrerequisiteApi'
export * as curriculumSuggestions from './curriculumSuggestionApi'
export * as exchange from './exchangeApi'
export * as feedback from './feedbackReportApi'
export * as studentSocial from './studentSocialApi'
export * as dailyMenu from './dailyMenuApi'
export * as sharedPeriodPlanning from './sharedPeriodPlanningApi'
export * as semesterPlanning from './semesterPlanningApi'
export * as studentInterests from './studentTagInterestApi'
export * as studentAbsences from './studentAbsenceApi'
export * as student from './studentApi'
export * as tagTaxonomy from './tagTaxonomyApi'
