/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SituacaoDoCursoRouteImport } from './routes/situacao-do-curso'
import { Route as PlanejamentosDeCurriculoRouteImport } from './routes/planejamentos-de-curriculo'
import { Route as MinhasSolicitacoesRouteImport } from './routes/minhas-solicitacoes'
import { Route as EditaisDeIntercambioRouteImport } from './routes/editais-de-intercambio'
import { Route as AmigosRouteImport } from './routes/amigos'
import { Route as DesignSystemRouteImport } from './routes/[_]design-system'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanejamentosDeSemestreIndexRouteImport } from './routes/planejamentos-de-semestre.index'
import { Route as PlanejamentosDeCurriculoIndexRouteImport } from './routes/planejamentos-de-curriculo.index'
import { Route as PlanejamentosDeSemestreNovoRouteImport } from './routes/planejamentos-de-semestre.novo'
import { Route as PlanejamentosDeSemestrePlanejamentoIdRouteImport } from './routes/planejamentos-de-semestre.$planejamentoId'
import { Route as PlanejamentosDeCurriculoNovoRouteImport } from './routes/planejamentos-de-curriculo.novo'
import { Route as PlanejamentosDeCurriculoPlanejamentoIdRouteImport } from './routes/planejamentos-de-curriculo.$planejamentoId'
import { Route as EditaisDeIntercambioConfiguracoesRouteImport } from './routes/editais-de-intercambio_.configuracoes'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SituacaoDoCursoRoute = SituacaoDoCursoRouteImport.update({
  id: '/situacao-do-curso',
  path: '/situacao-do-curso',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentosDeCurriculoRoute =
  PlanejamentosDeCurriculoRouteImport.update({
    id: '/planejamentos-de-curriculo',
    path: '/planejamentos-de-curriculo',
    getParentRoute: () => rootRouteImport,
  } as any)
const MinhasSolicitacoesRoute = MinhasSolicitacoesRouteImport.update({
  id: '/minhas-solicitacoes',
  path: '/minhas-solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisDeIntercambioRoute = EditaisDeIntercambioRouteImport.update({
  id: '/editais-de-intercambio',
  path: '/editais-de-intercambio',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosRoute = AmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/_design-system',
  path: '/_design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentosDeSemestreIndexRoute =
  PlanejamentosDeSemestreIndexRouteImport.update({
    id: '/planejamentos-de-semestre/',
    path: '/planejamentos-de-semestre/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlanejamentosDeCurriculoIndexRoute =
  PlanejamentosDeCurriculoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlanejamentosDeCurriculoRoute,
  } as any)
const PlanejamentosDeSemestreNovoRoute =
  PlanejamentosDeSemestreNovoRouteImport.update({
    id: '/planejamentos-de-semestre/novo',
    path: '/planejamentos-de-semestre/novo',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlanejamentosDeSemestrePlanejamentoIdRoute =
  PlanejamentosDeSemestrePlanejamentoIdRouteImport.update({
    id: '/planejamentos-de-semestre/$planejamentoId',
    path: '/planejamentos-de-semestre/$planejamentoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlanejamentosDeCurriculoNovoRoute =
  PlanejamentosDeCurriculoNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => PlanejamentosDeCurriculoRoute,
  } as any)
const PlanejamentosDeCurriculoPlanejamentoIdRoute =
  PlanejamentosDeCurriculoPlanejamentoIdRouteImport.update({
    id: '/$planejamentoId',
    path: '/$planejamentoId',
    getParentRoute: () => PlanejamentosDeCurriculoRoute,
  } as any)
const EditaisDeIntercambioConfiguracoesRoute =
  EditaisDeIntercambioConfiguracoesRouteImport.update({
    id: '/editais-de-intercambio_/configuracoes',
    path: '/editais-de-intercambio/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_design-system': typeof DesignSystemRoute
  '/amigos': typeof AmigosRoute
  '/editais-de-intercambio': typeof EditaisDeIntercambioRoute
  '/minhas-solicitacoes': typeof MinhasSolicitacoesRoute
  '/planejamentos-de-curriculo': typeof PlanejamentosDeCurriculoRouteWithChildren
  '/situacao-do-curso': typeof SituacaoDoCursoRoute
  '/sobre': typeof SobreRoute
  '/editais-de-intercambio/configuracoes': typeof EditaisDeIntercambioConfiguracoesRoute
  '/planejamentos-de-curriculo/$planejamentoId': typeof PlanejamentosDeCurriculoPlanejamentoIdRoute
  '/planejamentos-de-curriculo/novo': typeof PlanejamentosDeCurriculoNovoRoute
  '/planejamentos-de-semestre/$planejamentoId': typeof PlanejamentosDeSemestrePlanejamentoIdRoute
  '/planejamentos-de-semestre/novo': typeof PlanejamentosDeSemestreNovoRoute
  '/planejamentos-de-curriculo/': typeof PlanejamentosDeCurriculoIndexRoute
  '/planejamentos-de-semestre': typeof PlanejamentosDeSemestreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/_design-system': typeof DesignSystemRoute
  '/amigos': typeof AmigosRoute
  '/editais-de-intercambio': typeof EditaisDeIntercambioRoute
  '/minhas-solicitacoes': typeof MinhasSolicitacoesRoute
  '/situacao-do-curso': typeof SituacaoDoCursoRoute
  '/sobre': typeof SobreRoute
  '/editais-de-intercambio/configuracoes': typeof EditaisDeIntercambioConfiguracoesRoute
  '/planejamentos-de-curriculo/$planejamentoId': typeof PlanejamentosDeCurriculoPlanejamentoIdRoute
  '/planejamentos-de-curriculo/novo': typeof PlanejamentosDeCurriculoNovoRoute
  '/planejamentos-de-semestre/$planejamentoId': typeof PlanejamentosDeSemestrePlanejamentoIdRoute
  '/planejamentos-de-semestre/novo': typeof PlanejamentosDeSemestreNovoRoute
  '/planejamentos-de-curriculo': typeof PlanejamentosDeCurriculoIndexRoute
  '/planejamentos-de-semestre': typeof PlanejamentosDeSemestreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_design-system': typeof DesignSystemRoute
  '/amigos': typeof AmigosRoute
  '/editais-de-intercambio': typeof EditaisDeIntercambioRoute
  '/minhas-solicitacoes': typeof MinhasSolicitacoesRoute
  '/planejamentos-de-curriculo': typeof PlanejamentosDeCurriculoRouteWithChildren
  '/situacao-do-curso': typeof SituacaoDoCursoRoute
  '/sobre': typeof SobreRoute
  '/editais-de-intercambio_/configuracoes': typeof EditaisDeIntercambioConfiguracoesRoute
  '/planejamentos-de-curriculo/$planejamentoId': typeof PlanejamentosDeCurriculoPlanejamentoIdRoute
  '/planejamentos-de-curriculo/novo': typeof PlanejamentosDeCurriculoNovoRoute
  '/planejamentos-de-semestre/$planejamentoId': typeof PlanejamentosDeSemestrePlanejamentoIdRoute
  '/planejamentos-de-semestre/novo': typeof PlanejamentosDeSemestreNovoRoute
  '/planejamentos-de-curriculo/': typeof PlanejamentosDeCurriculoIndexRoute
  '/planejamentos-de-semestre/': typeof PlanejamentosDeSemestreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_design-system'
    | '/amigos'
    | '/editais-de-intercambio'
    | '/minhas-solicitacoes'
    | '/planejamentos-de-curriculo'
    | '/situacao-do-curso'
    | '/sobre'
    | '/editais-de-intercambio/configuracoes'
    | '/planejamentos-de-curriculo/$planejamentoId'
    | '/planejamentos-de-curriculo/novo'
    | '/planejamentos-de-semestre/$planejamentoId'
    | '/planejamentos-de-semestre/novo'
    | '/planejamentos-de-curriculo/'
    | '/planejamentos-de-semestre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/_design-system'
    | '/amigos'
    | '/editais-de-intercambio'
    | '/minhas-solicitacoes'
    | '/situacao-do-curso'
    | '/sobre'
    | '/editais-de-intercambio/configuracoes'
    | '/planejamentos-de-curriculo/$planejamentoId'
    | '/planejamentos-de-curriculo/novo'
    | '/planejamentos-de-semestre/$planejamentoId'
    | '/planejamentos-de-semestre/novo'
    | '/planejamentos-de-curriculo'
    | '/planejamentos-de-semestre'
  id:
    | '__root__'
    | '/'
    | '/_design-system'
    | '/amigos'
    | '/editais-de-intercambio'
    | '/minhas-solicitacoes'
    | '/planejamentos-de-curriculo'
    | '/situacao-do-curso'
    | '/sobre'
    | '/editais-de-intercambio_/configuracoes'
    | '/planejamentos-de-curriculo/$planejamentoId'
    | '/planejamentos-de-curriculo/novo'
    | '/planejamentos-de-semestre/$planejamentoId'
    | '/planejamentos-de-semestre/novo'
    | '/planejamentos-de-curriculo/'
    | '/planejamentos-de-semestre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  AmigosRoute: typeof AmigosRoute
  EditaisDeIntercambioRoute: typeof EditaisDeIntercambioRoute
  MinhasSolicitacoesRoute: typeof MinhasSolicitacoesRoute
  PlanejamentosDeCurriculoRoute: typeof PlanejamentosDeCurriculoRouteWithChildren
  SituacaoDoCursoRoute: typeof SituacaoDoCursoRoute
  SobreRoute: typeof SobreRoute
  EditaisDeIntercambioConfiguracoesRoute: typeof EditaisDeIntercambioConfiguracoesRoute
  PlanejamentosDeSemestrePlanejamentoIdRoute: typeof PlanejamentosDeSemestrePlanejamentoIdRoute
  PlanejamentosDeSemestreNovoRoute: typeof PlanejamentosDeSemestreNovoRoute
  PlanejamentosDeSemestreIndexRoute: typeof PlanejamentosDeSemestreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situacao-do-curso': {
      id: '/situacao-do-curso'
      path: '/situacao-do-curso'
      fullPath: '/situacao-do-curso'
      preLoaderRoute: typeof SituacaoDoCursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamentos-de-curriculo': {
      id: '/planejamentos-de-curriculo'
      path: '/planejamentos-de-curriculo'
      fullPath: '/planejamentos-de-curriculo'
      preLoaderRoute: typeof PlanejamentosDeCurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-solicitacoes': {
      id: '/minhas-solicitacoes'
      path: '/minhas-solicitacoes'
      fullPath: '/minhas-solicitacoes'
      preLoaderRoute: typeof MinhasSolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais-de-intercambio': {
      id: '/editais-de-intercambio'
      path: '/editais-de-intercambio'
      fullPath: '/editais-de-intercambio'
      preLoaderRoute: typeof EditaisDeIntercambioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos': {
      id: '/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AmigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_design-system': {
      id: '/_design-system'
      path: '/_design-system'
      fullPath: '/_design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamentos-de-semestre/': {
      id: '/planejamentos-de-semestre/'
      path: '/planejamentos-de-semestre'
      fullPath: '/planejamentos-de-semestre'
      preLoaderRoute: typeof PlanejamentosDeSemestreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamentos-de-curriculo/': {
      id: '/planejamentos-de-curriculo/'
      path: '/'
      fullPath: '/planejamentos-de-curriculo/'
      preLoaderRoute: typeof PlanejamentosDeCurriculoIndexRouteImport
      parentRoute: typeof PlanejamentosDeCurriculoRoute
    }
    '/planejamentos-de-semestre/novo': {
      id: '/planejamentos-de-semestre/novo'
      path: '/planejamentos-de-semestre/novo'
      fullPath: '/planejamentos-de-semestre/novo'
      preLoaderRoute: typeof PlanejamentosDeSemestreNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamentos-de-semestre/$planejamentoId': {
      id: '/planejamentos-de-semestre/$planejamentoId'
      path: '/planejamentos-de-semestre/$planejamentoId'
      fullPath: '/planejamentos-de-semestre/$planejamentoId'
      preLoaderRoute: typeof PlanejamentosDeSemestrePlanejamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamentos-de-curriculo/novo': {
      id: '/planejamentos-de-curriculo/novo'
      path: '/novo'
      fullPath: '/planejamentos-de-curriculo/novo'
      preLoaderRoute: typeof PlanejamentosDeCurriculoNovoRouteImport
      parentRoute: typeof PlanejamentosDeCurriculoRoute
    }
    '/planejamentos-de-curriculo/$planejamentoId': {
      id: '/planejamentos-de-curriculo/$planejamentoId'
      path: '/$planejamentoId'
      fullPath: '/planejamentos-de-curriculo/$planejamentoId'
      preLoaderRoute: typeof PlanejamentosDeCurriculoPlanejamentoIdRouteImport
      parentRoute: typeof PlanejamentosDeCurriculoRoute
    }
    '/editais-de-intercambio_/configuracoes': {
      id: '/editais-de-intercambio_/configuracoes'
      path: '/editais-de-intercambio/configuracoes'
      fullPath: '/editais-de-intercambio/configuracoes'
      preLoaderRoute: typeof EditaisDeIntercambioConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlanejamentosDeCurriculoRouteChildren {
  PlanejamentosDeCurriculoPlanejamentoIdRoute: typeof PlanejamentosDeCurriculoPlanejamentoIdRoute
  PlanejamentosDeCurriculoNovoRoute: typeof PlanejamentosDeCurriculoNovoRoute
  PlanejamentosDeCurriculoIndexRoute: typeof PlanejamentosDeCurriculoIndexRoute
}

const PlanejamentosDeCurriculoRouteChildren: PlanejamentosDeCurriculoRouteChildren =
  {
    PlanejamentosDeCurriculoPlanejamentoIdRoute:
      PlanejamentosDeCurriculoPlanejamentoIdRoute,
    PlanejamentosDeCurriculoNovoRoute: PlanejamentosDeCurriculoNovoRoute,
    PlanejamentosDeCurriculoIndexRoute: PlanejamentosDeCurriculoIndexRoute,
  }

const PlanejamentosDeCurriculoRouteWithChildren =
  PlanejamentosDeCurriculoRoute._addFileChildren(
    PlanejamentosDeCurriculoRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  AmigosRoute: AmigosRoute,
  EditaisDeIntercambioRoute: EditaisDeIntercambioRoute,
  MinhasSolicitacoesRoute: MinhasSolicitacoesRoute,
  PlanejamentosDeCurriculoRoute: PlanejamentosDeCurriculoRouteWithChildren,
  SituacaoDoCursoRoute: SituacaoDoCursoRoute,
  SobreRoute: SobreRoute,
  EditaisDeIntercambioConfiguracoesRoute:
    EditaisDeIntercambioConfiguracoesRoute,
  PlanejamentosDeSemestrePlanejamentoIdRoute:
    PlanejamentosDeSemestrePlanejamentoIdRoute,
  PlanejamentosDeSemestreNovoRoute: PlanejamentosDeSemestreNovoRoute,
  PlanejamentosDeSemestreIndexRoute: PlanejamentosDeSemestreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
