/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/[_]design-system'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanejamentosPlanejamentoIdRouteImport } from './routes/planejamentos.$planejamentoId'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/_design-system',
  path: '/_design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentosPlanejamentoIdRoute =
  PlanejamentosPlanejamentoIdRouteImport.update({
    id: '/planejamentos/$planejamentoId',
    path: '/planejamentos/$planejamentoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_design-system': typeof DesignSystemRoute
  '/planejamentos/$planejamentoId': typeof PlanejamentosPlanejamentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/_design-system': typeof DesignSystemRoute
  '/planejamentos/$planejamentoId': typeof PlanejamentosPlanejamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_design-system': typeof DesignSystemRoute
  '/planejamentos/$planejamentoId': typeof PlanejamentosPlanejamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/_design-system' | '/planejamentos/$planejamentoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/_design-system' | '/planejamentos/$planejamentoId'
  id: '__root__' | '/' | '/_design-system' | '/planejamentos/$planejamentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  PlanejamentosPlanejamentoIdRoute: typeof PlanejamentosPlanejamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_design-system': {
      id: '/_design-system'
      path: '/_design-system'
      fullPath: '/_design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamentos/$planejamentoId': {
      id: '/planejamentos/$planejamentoId'
      path: '/planejamentos/$planejamentoId'
      fullPath: '/planejamentos/$planejamentoId'
      preLoaderRoute: typeof PlanejamentosPlanejamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  PlanejamentosPlanejamentoIdRoute: PlanejamentosPlanejamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
